{\rtf1\ansi\ansicpg1252\cocoartf2818
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red24\green26\blue30;\red24\green26\blue30;}
{\*\expandedcolortbl;;\cssrgb\c12157\c13725\c15686;\cssrgb\c12157\c13725\c15686;}
\paperw8400\paperh11900\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 theme: 
\fs27\fsmilli13600 \cf3 \outl0\strokewidth0 All in Web3 (hiring & recruitment)
\fs27\fsmilli13600 \cf2 \outl0\strokewidth0 \strokec2 \
title: All in Web3 (hiring & recruitment)\
description: Bookmark this to keep an eye on updates!\
}